### ISSUE TITLE
delete absmag_comovingdist_functions.py

### ISSUE THREAD

**Issue by QuiteAFoxtrot** [DESI-UR/Voids#5]
The functionality of this module has been superseded by the faster cython version in dist_funcs_cython.py

best solution would probably be to remove the absmag_comovingdist_functions.py and rename

dist_funcs_cython.pyx -> distance.pyx so users can do 'from voidfinder.distance import z_to_comoving_dist' and such

**Comment by kadglass** [comment]
`absmag_comovingdist_functions.py` has been moved to the `legacy` folder, and `dist_funcs_cython.pyx` has been renamed to `distance.pyx`.
